name: Tests

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule update --init --recursive --depth=1

    - name: Install Dependencies
      run: |
        python3 -m pip install -U pip setuptools

    - name: Install
      run: |
        python3 -m pip install --user .
